spring:
  application:
    name: StockSync Backend
  config:
    import: "optional:file:.env[.properties]"
  thymeleaf:
    cache: false


  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    # Si la base de datos ya tiene tablas creadas manualmente, activa esto:
    baseline-on-migrate: true


# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    org.springframework.security: INFO
    root: INFO
    com.stockSync:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Esta sección va aparte, NO dentro de spring:
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

